### ISSUE TITLE
Errors installing pclpy tree tool package dependencies

### ISSUE THREAD

**Issue by Masilokwa-bantu** [porteratzo/TreeTool#13]
Hello Porterato,

Thank you so much for developing this tool. I am using a windows machine and currently trying to get tree tools working and I have tried several approaches to install it. I already have anaconda installed on my device and when I tried to use the environement.yml file to create a new environment I encountered the error shown below.

(base) PS C:\Users\Vincent\PycharmProjects\TreeTool> conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - conda-forge/label/gcc7::qhull

I then tried to install the dependencies individually, updated the conda, added the listed channels and installed the dependencies. However, when using my IDE (PyCharm) and running the QuickDemo Jupyter notebook the module pclpy is not found when I had it installed.

Error from IDE:
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pclpy
      2 import numpy as np
      3 import treetool.seg_tree as seg_tree

ModuleNotFoundError: No module named 'pclpy'

This is the error I get when running python in the terminal within the treetool environment with the installed dependencies from the environment.yml file.

>>> import pclpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Vincent\anaconda3\envs\treetool\lib\site-packages\pclpy\__init__.py", line 3, in <module>
    import pclpy.pcl as pcl
ImportError: DLL load failed: The specified module could not be found.

From the error it seems as though pcl which I presume is the C++ library does not install when pclpy is installed. However, from the documentation on pclpy it states that all the dependencies should be installed automatically when pclpy is installed.

Please could you assist me with the installation currently require the tool for a project and working on a tight timline. Any assistance that you can provide is greatly appreciated. Hope to here from you.

**Comment by sudo-paras-shah** [comment]
Yes I am getting the same error. So I searched pclpy online and turns out that the PyPI documentation mentions that pclpy only works with Python version 3.6 as of August 13, 2024 but the requirements for TreeTool mention that it needs Python 3.8

pclpy: 

> Only Windows and python 3.6 x64 are supported at the moment.

**Comment by porteratzo** [comment]
We are currently refactoring treetool to not use pclpy which has not been updated 3 years and can be a real hassle to get working

**Comment by sudo-paras-shah** [comment]
> We are currently refactoring treetool to not use pclpy which has not been updated 3 years and can be a real hassle to get working

Ok so I tried changing python version and it worked with Python3.7 So you can just change the environment.yml file to this:
```
# run: conda env create --file environment.yml
name: treetool
channels:
  - "conda-forge"
  - "davidcaron"
  - "conda-forge/label/gcc7"
dependencies:
- python=3.7
- davidcaron::pclpy
- conda-forge/label/gcc::qhull
- jupyter
- ipykernel
- matplotlib
- pip
- pip:
  - treetool
```

Good luck with the refactoring 👍

**Comment by porteratzo** [comment]
Treetool now works with python3.10 and should be much easier to install with conda env create
